### ISSUE TITLE
Feature request: step backward while keeping robot status valid

### ISSUE THREAD

**Issue by rpvs73** [PlotJuggler/PlotJuggler#257]
We have a configuration with PlotJuggler and RViz displaying a robot. When clicking on the time slider and then pressing left and right keys on the keyboard, it is possible to move one step backward or forward. 

However, for stepping backwards this requires two steps backward and one step forward to have RViz pick up the new simulation time and render the new state. When only stepping backward from PlotJuggler the robot status in RViz changes to 'Error' (caused by a tf time error).

In the attached movie, you can see that the status of the RobotModel changes to 'Error' when doing a number of steps back in time. The status will change back to 'Ok' on the first step forward.

Do you have a solution for this?

[tf_time_error.zip](https://github.com/facontidavide/PlotJuggler/files/4273677/tf_time_error.zip)

**Comment by facontidavide** [comment]
Just to confirm... Are you setting use_sim_time?

**Comment by rpvs73** [comment]
Yes, 'use_sim_time' is set to 'true'

**Comment by facontidavide** [comment]
close due to inactivity and lack of interest
